### PR TITLE
Add Gatsby Astronaut placeholder image

### PR DESCRIPTION
**Pull request by barrymcgee**
Adding this image will allow users to add a relative src to add an image to their page in the Part 1 Tutorial here: https://www.gatsbyjs.org/tutorial/part-one/

See discussion here: https://github.com/gatsbyjs/gatsby/issues/9655

## How to QA

- If you haven't already, globally install the [gatsby-cli](https://www.npmjs.com/package/gatsby-cli); `npm install --global gatsby-cli`
- Run: `gatsby new gatsby-astronaut-pr https://github.com/barrymcgee/gatsby-starter-hello-world/`
- Drop into that folder; `cd gatsby-astronaut-pr`
- Run the starter; `npm start`
- View the site in your browser at; [http://localhost:8000/](http://localhost:8000/)
- You should just see "Hello world"
- Open the site folder in your editor and find; `src/pages/index.js`
- Replace it's contents with;

```
import React from "react"

export default () => (
  <div style={{ color: `purple` }}>
    <h1>Hello Gatsby!</h1>
    <p>What a world.</p>
    <img src="./images/gatsby-astronaut.png" alt="The Gatsby Astronaut illustration" />
  </div>
)

```

Switching back to your browser; [http://localhost:8000/](http://localhost:8000/) should now look like the screenshot below;

screenshot 2018-11-05 at 13 07 07

### CODE REVIEW

**Comment by barrymcgee** [comment]
@tanvibhakta Would you be able to QA this change for me please? 

It will then unblock https://github.com/gatsbyjs/gatsby/pull/9698 which will resolve https://github.com/gatsbyjs/gatsby/issues/9655

**Comment by tanvibhakta** [comment]
Hello! I will do this in 48 hours, hope that's okay. My family celebrated
Deepavali so I'm trying not to use much tech today.

**Comment by ebello** [comment]
Hi there! Just following up on this, is it ready to merge?

**Comment by barrymcgee** [comment]
Hi @tanvibhakta, do you have any bandwidth this week to review this please? Maybe if you're super busy, @shannonbux could take a look?

**Comment by shannonbux** [comment]
Hello everyone! Thanks for your hard work here and apologies for the time it took to reach a decision on this PR and the connected one (https://github.com/gatsbyjs/gatsby/pull/9698). For now, I'm going to close this in favor of https://github.com/gatsbyjs/gatsby/issues/9374 since a adding a page to the tutorial specifically on gatsby-image introduces a best practice. Thanks in advance for your patience with this idea; we only recently realized how few people know about gatsby-image and we'd like to use the tutorial as one of the ways to teach about it.

It will be valuable to get your input on that new `gatsby-image` tutorial and honestly, if any of you feels up to reviewing all the image-related docs and cleaning them up, they could use it!

Here's the issue for cleaning those up!
https://github.com/gatsbyjs/gatsby/issues/4319

**Pull request closed without merging**
